import {BALANCE as B,PLANTS,ZOMBIES,UPGRADES} from './data.js';
export class Game{
 constructor(meta,onWave,onEnd){this.meta=meta;this.onWave=onWave;this.onEnd=onEnd;this.reset()}
 reset(){this.state='ready';this.wave=0;this.sun=B.startSun+this.meta.economy*10;this.food=0;this.maxHp=B.baseHp*(1+this.meta.fortress*.05);this.hp=this.maxHp;this.plants=[];this.zombies=[];this.shots=[];this.effects=[];this.levels=Object.fromEntries(PLANTS.map(p=>[p.id,1]));this.mods={damage:1+this.meta.mastery*.02,hp:1,range:1,haste:1,sun:1,costDiscount:0};this.upgrades=[];this.kills=0;this.time=0;this.generated=0;this.placed=0;this.collected=0;this.sunTimer=0;this.queue=0;this.spawnTimer=0;this.speed=1;this.paused=false;this.nextId=0;this.earned=0;this.plantRevision=0}
 stats(p){const level=this.levels[p.id]-1;return {...p,hp:p.hp*this.mods.hp*(1+level*.15),damage:p.damage*this.mods.damage*(1+level*.1),interval:p.interval/(this.mods.haste*(1+level*.05)),range:p.range*this.mods.range,sun:25*this.mods.sun*(1+level*.15)}}
 fieldCount(id){return this.plants.filter(p=>p.id===id&&p.hp>0).length}
 getPlantCost(id){const p=PLANTS.find(p=>p.id===id);if(!p)return Infinity;const cfg=B.plantCostScaling,mult=p.costGrowth??cfg.defaultMultiplier,count=this.fieldCount(id);const scaled=cfg.enabled?Math.round(p.baseCost*Math.pow(mult,count)):p.baseCost;const discount=Math.min(cfg.maxDiscount,Math.max(0,this.mods.costDiscount||0));return Math.round(scaled*(1-discount))}
 occupied(x,y){return this.plants.find(p=>p.x===x&&p.y===y&&p.hp>0)}
 valid(x,y){return Number.isInteger(x)&&Number.isInteger(y)&&x>0&&y>0&&x<B.cols-1&&y<B.rows-1&&!(x>=9&&x<=10&&y>=6&&y<=7)&&!this.occupied(x,y)&&!this.zombies.some(z=>Math.floor(z.x)===x&&Math.floor(z.y)===y)}
 place(id,x,y){const def=PLANTS.find(p=>p.id===id),cost=this.getPlantCost(id);if(!def||!['ready','playing'].includes(this.state)||this.paused||!this.valid(x,y)||this.sun<cost)return false;this.sun-=cost;const s=this.stats(def);this.plants.push({...def,x,y,hp:s.hp,maxHp:s.hp,timer:0,age:0,uid:++this.nextId});this.placed++;this.plantRevision++;return true}
 startWave(){if(this.state!=='ready'||this.paused)return false;this.wave++;this.state='playing';this.queue=5+Math.floor((this.wave-1)*1.6);this.spawnTimer=0;return true}
 spawn(){let tier=0;const r=Math.random();if(this.wave>=5&&r<Math.min(.4,.12+(this.wave-5)*.015))tier=2;else if(this.wave>=3&&r<.6)tier=1;const d=ZOMBIES[tier],side=Math.floor(Math.random()*4);let x=.5+Math.floor(Math.random()*B.cols),y=.5+Math.floor(Math.random()*B.rows);if(side===0)y=.15;if(side===1)x=B.cols-.15;if(side===2)y=B.rows-.15;if(side===3)x=.15;const scale=1+(this.wave-1)*.1;this.zombies.push({...d,x,y,tier,hp:d.hp*scale,maxHp:d.hp*scale,speed:d.speed*Math.min(1.5,1+(this.wave-1)*.008),damage:d.damage*(1+(this.wave-1)*.04),cool:0,uid:++this.nextId,flash:0})}
 damage(z,amount){if(z.hp<=0)return;z.hp-=amount;z.flash=.12;if(z.hp<=0){this.kills++;this.effects.push({x:z.x,y:z.y,t:.35,max:.35,color:'#d9eaac',r:.45})}}
 plantFood(id){const level=this.levels[id];if(!level||level>=5||this.food<level||!['ready','playing'].includes(this.state))return false;this.food-=level;this.levels[id]++;for(const p of this.plants.filter(p=>p.id===id)){const n=this.stats(p).hp;p.hp+=n-p.maxHp;p.maxHp=n}return true}
 upgrade(u){if(this.state!=='upgrade')return false;if(u.key==='heal')this.hp=Math.min(this.maxHp,this.hp+this.maxHp*u.value);else{this.mods[u.key]*=u.value;if(u.key==='hp')for(const p of this.plants){p.hp*=u.value;p.maxHp*=u.value}}this.upgrades.push(u.name);this.state='ready';return true}
 step(dt){if(this.paused||!['playing','ready'].includes(this.state))return;this.time+=dt;this.sunTimer+=dt;if(this.sunTimer>=B.naturalInterval){this.sunTimer-=B.naturalInterval;const n=Math.round(B.naturalSun*this.mods.sun);this.sun+=n;this.generated+=n}for(const p of this.plants){p.age+=dt;p.timer-=dt;const s=this.stats(p);if(p.id==='sunflower'&&p.timer<=0){p.timer=s.interval;if(p.age<.2)continue;const n=Math.round(s.sun);this.sun+=n;this.generated+=n;this.effects.push({x:p.x+.5,y:p.y+.5,t:.6,max:.6,color:'#ffdb65',r:.7})}if(this.state!=='playing'||!s.damage)continue;const near=this.zombies.filter(z=>z.hp>0&&Math.hypot(z.x-p.x-.5,z.y-p.y-.5)<=s.range).sort((a,b)=>Math.hypot(a.x-10,a.y-7)-Math.hypot(b.x-10,b.y-7));if(!near.length||p.timer>0)continue;if(p.id==='potatoMine'){if(p.age<4)continue;for(const z of this.zombies)if(Math.hypot(z.x-p.x-.5,z.y-p.y-.5)<1.7)this.damage(z,s.damage);p.hp=0;this.effects.push({x:p.x+.5,y:p.y+.5,t:.45,max:.45,color:'#fbc479',r:1.7});continue}p.timer=s.interval;const target=near[0];if(p.id==='bonkChoy'){this.damage(target,s.damage);this.effects.push({x:target.x,y:target.y,t:.15,max:.15,color:p.color,r:.5})}else for(let i=0;i<(p.id==='repeater'?2:1);i++)this.shots.push({x:p.x+.5,y:p.y+.5+i*.15,target,damage:s.damage,splash:p.id==='cabbagePult',color:p.color,life:3})}
 if(this.state==='playing'){this.spawnTimer-=dt;if(this.queue>0&&this.spawnTimer<=0){this.spawn();this.queue--;this.spawnTimer=Math.max(.28,1.1-this.wave*.02)}for(const z of this.zombies){if(z.hp<=0)continue;z.cool-=dt;z.flash=Math.max(0,z.flash-dt);let target={x:10,y:7,base:true};let closest=Infinity;for(const p of this.plants){if(p.hp<=0)continue;const d=Math.hypot(p.x+.5-z.x,p.y+.5-z.y);if(d<.86&&d<closest){closest=d;target=p}}let tx=target.base?10:target.x+.5,ty=target.base?7:target.y+.5;const dist=Math.hypot(tx-z.x,ty-z.y),reach=target.base?1.3:.86;if(dist<=reach){if(z.cool<=0){z.cool=1;if(target.base)this.hp-=z.damage;else target.hp-=z.damage}}else{let dx=(tx-z.x)/dist*z.speed*dt,dy=(ty-z.y)/dist*z.speed*dt;const blocker=this.plants.find(p=>p.hp>0&&Math.hypot(z.x+dx-p.x-.5,z.y+dy-p.y-.5)<.7);if(!blocker){z.x+=dx;z.y+=dy}}}for(const s of this.shots){s.life-=dt;if(s.target.hp<=0){s.life=0;continue}const dx=s.target.x-s.x,dy=s.target.y-s.y,d=Math.hypot(dx,dy),move=(s.splash?6:9)*dt;if(d<=move){if(s.splash){for(const z of this.zombies)if(Math.hypot(z.x-s.target.x,z.y-s.target.y)<1.2)this.damage(z,s.damage);this.effects.push({x:s.target.x,y:s.target.y,t:.3,max:.3,color:'#b7e889',r:1.2})}else this.damage(s.target,s.damage);s.life=0}else{s.x+=dx/d*move;s.y+=dy/d*move}}this.shots=this.shots.filter(s=>s.life>0);this.zombies=this.zombies.filter(z=>z.hp>0);if(this.hp<=0){this.hp=0;this.state='over';this.earned=this.wave*3+Math.floor(this.kills/4)+Math.floor(this.time/60);this.onEnd();return}if(this.queue===0&&this.zombies.length===0){this.food++;this.collected++;this.state='upgrade';this.shots=[];this.onWave([...UPGRADES].sort(()=>Math.random()-.5).slice(0,3))}}
 const living=this.plants.filter(p=>p.hp>0);if(living.length!==this.plants.length)this.plantRevision++;this.plants=living;this.effects.forEach(e=>e.t-=dt);this.effects=this.effects.filter(e=>e.t>0)}
}
