import {Game} from './game.js';import {render} from './render.js';import {PLANTS,BALANCE} from './data.js';import {read,write,validate,download,fresh} from './save.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),modal=$('modal');let meta=read(),selected='peashooter',hover=null,inspected=null,toastTimer,last=performance.now(),acc=0,lastPlantRevision=-1;
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function persist(){if(!write(meta))toast('Não foi possível salvar no navegador. Exporte seu save TXT.')}
function show(html){$('modal-content').innerHTML=html;if(!modal.open)modal.showModal()}
function close(){modal.close()}
const g=new Game(meta,choices=>{show('<small>WAVE '+g.wave+' CONCLUÍDA · +1 PLANT FOOD</small><h2>Seu jardim evoluiu.</h2><p>Escolha um upgrade. Os bônus se acumulam nesta run.</p><div class="choices">'+choices.map((u,i)=>'<button data-upgrade="'+i+'"><b>'+u.name+'</b><span>'+u.desc+'</span></button>').join('')+'</div>');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{g.upgrade(choices[Number(b.dataset.upgrade)]);close();update()})},()=>{meta.seeds+=g.earned;meta.highestWave=Math.max(meta.highestWave,g.wave);meta.totalRuns++;meta.kills+=g.kills;meta.time+=Math.floor(g.time);persist();show('<small>FIM DA RUN</small><h2>O jardim caiu.<br>A próxima defesa será melhor.</h2><p>Wave '+g.wave+' · '+g.kills+' abates · '+clock(g.time)+' sobrevividos<br>'+g.placed+' plantas · '+g.generated+' Sun gerados · '+g.collected+' Plant Food coletados</p><h3>+'+g.earned+' Seeds</h3><button class="primary" id="again">Jogar novamente →</button><button id="endmenu">Menu e melhorias</button>');$('again').onclick=newRun;$('endmenu').onclick=menu});
function newRun(){g.meta=meta;g.reset();selected='peashooter';inspected=null;close();update();toast('Plante Sunflowers e defesas antes de iniciar a wave.')}
function clock(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0')}
$('plants').innerHTML=PLANTS.map((p,i)=>'<button class="plant-card" data-plant="'+p.id+'"><span class="hotkey">'+(i+1)+'</span><span class="unit-icon" style="color:'+p.color+'">'+p.mark+'</span><span class="name">'+p.name+'</span><span class="field-count" data-count-for="'+p.id+'"></span><span class="cost" data-cost-for="'+p.id+'"></span></button>').join('');
document.querySelectorAll('[data-plant]').forEach(b=>b.onclick=()=>{selected=b.dataset.plant;inspected=null;update()});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();hover={x:Math.floor((e.clientX-r.left)/r.width*20),y:Math.floor((e.clientY-r.top)/r.height*14)}});canvas.addEventListener('pointerleave',()=>hover=null);canvas.addEventListener('click',e=>{if(modal.open)return;const r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*20),y=Math.floor((e.clientY-r.top)/r.height*14),p=g.occupied(x,y);if(p){inspected=p;selected=null;update();return}if(selected&&!g.place(selected,x,y))toast(g.paused?'Retome a run para plantar.':'Tile ocupado, borda protegida ou Sun insuficiente.');update()});
$('next').onclick=()=>{g.startWave();update()};$('pause').onclick=()=>{if(!modal.open){g.paused=!g.paused;update()}};$('speed').onclick=()=>{g.speed=g.speed%3+1;update()};$('menu').onclick=menu;
document.addEventListener('keydown',e=>{if(modal.open)return;if(e.code==='Space'){e.preventDefault();$('pause').click()}if(e.key==='Escape'){selected=null;inspected=null}if(/^[1-7]$/.test(e.key)){selected=PLANTS[Number(e.key)-1].id;inspected=null}update()});
modal.addEventListener('cancel',e=>{e.preventDefault();if(g.state==='ready'||g.state==='playing'){close();g.paused=false;update()}});document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden&&g.state==='playing'){g.paused=true;update()}});
function update(){for(const [id,v] of Object.entries({wave:String(Math.max(1,g.wave)).padStart(2,'0'),sun:Math.floor(g.sun),food:g.food,hp:Math.ceil(g.hp)+' / '+Math.ceil(g.maxHp),enemies:g.zombies.length+g.queue,kills:g.kills,time:clock(g.time),record:meta.highestWave}))$(id).textContent=v;$('health').max=g.maxHp;$('health').value=g.hp;$('pause').textContent=g.paused?'Retomar':'Pausar';$('speed').textContent=g.speed+'×';$('next').disabled=g.state!=='ready'||g.paused;$('next').innerHTML=g.state==='ready'?'Iniciar wave '+(g.wave+1)+' <span>→</span>':g.state==='playing'?'Wave em andamento':'Wave encerrada';$('status').textContent=g.paused?'RUN PAUSADA':g.state==='ready'?'PREPARE SUA DEFESA':'SOBREVIVA À WAVE '+g.wave;document.querySelectorAll('[data-plant]').forEach(b=>{const p=PLANTS.find(p=>p.id===b.dataset.plant),count=g.fieldCount(p.id),cost=g.getPlantCost(p.id),growth=Math.round(((p.costGrowth??BALANCE.plantCostScaling.defaultMultiplier)-1)*100),costEl=b.querySelector('[data-cost-for]'),previous=Number(b.dataset.lastCost);b.classList.toggle('selected',p.id===selected);b.disabled=g.sun<cost;if(previous&&previous!==cost){costEl.classList.remove('cost-flash');void costEl.offsetWidth;costEl.classList.add('cost-flash')}b.dataset.lastCost=cost;costEl.textContent='☀ '+cost;b.querySelector('[data-count-for]').textContent=count?'×'+count+' NO CAMPO':'';b.title=p.description+'\nCusto base: '+p.baseCost+' Sun\nNo campo: '+count+'\nPróxima planta: '+cost+' Sun\nCrescimento: +'+growth+'% por '+p.name});const p=inspected&&g.plants.includes(inspected)?inspected:PLANTS.find(p=>p.id===selected);if(p){const s=g.stats(p),lv=g.levels[p.id];$('inspect').innerHTML='<h2>'+p.name+' <small>LEVEL '+lv+' / 5</small></h2><p>'+p.description+'<br>'+(s.damage?Math.round(s.damage)+' dano · '+s.range.toFixed(1)+' alcance':Math.round(s.hp)+' HP')+'<br>Próxima unidade: '+g.getPlantCost(p.id)+' Sun'+(inspected?'<br>Vida: '+Math.ceil(inspected.hp)+' / '+Math.ceil(inspected.maxHp):'')+'</p><button id="feed" '+(lv>=5||g.food<lv?'disabled':'')+'>'+(lv>=5?'Nível máximo':'Evoluir espécie · '+lv+' Plant Food')+'</button>';$('feed').onclick=()=>{if(g.plantFood(p.id)){toast('Espécie evoluída para esta run!');update()}}}else $('inspect').innerHTML='<h2>Escolha sua defesa</h2><p>Selecione um card ou inspecione uma planta no mapa.</p>';const counts={};g.upgrades.forEach(u=>counts[u]=(counts[u]||0)+1);$('upgrades').innerHTML=Object.entries(counts).map(([u,n])=>'<div class="upgrade-pill">'+u+(n>1?' ×'+n:'')+'</div>').join('')||'<p>Complete waves para escolher upgrades.</p>'}
function menu(){g.paused=true;show('<small>GARDEN / LAST STAND</small><h2>Uma semente.<br>Mais uma chance.</h2><p>Construa sua defesa, sobreviva às waves e evolua entre runs.</p><button class="primary" id="play">'+(g.state==='over'?'Nova run':'Entrar no jardim')+' →</button><div class="menu-grid"><button id="meta">Melhorias · '+meta.seeds+' Seeds</button><button id="almanac">Garden Almanac</button><button id="stats">Estatísticas</button><button id="export">Exportar save TXT</button><button id="import-btn">Importar save TXT</button><button id="save">Salvar progresso</button><button id="reset">Resetar save</button></div><p style="font-size:12px">O save guarda progresso permanente, não a run em andamento. Sem login. Salvo neste navegador.</p>');$('play').onclick=()=>{if(g.state==='over')newRun();else{g.paused=false;close();update()}};$('meta').onclick=metaMenu;$('almanac').onclick=almanac;$('stats').onclick=()=>{show('<small>ESTATÍSTICAS PERMANENTES</small><h2>Seu histórico</h2><p>Maior wave: '+meta.highestWave+'<br>Runs concluídas: '+meta.totalRuns+'<br>Zumbis derrotados: '+meta.kills+'<br>Tempo: '+clock(meta.time)+'<br>Seeds: '+meta.seeds+'</p><button id="back">Voltar</button>');$('back').onclick=menu};$('export').onclick=()=>download(meta);$('import-btn').onclick=()=>$('import').click();$('save').onclick=()=>{persist();toast('Progresso permanente salvo.')};$('reset').onclick=()=>{if(confirm('Apagar todo o progresso permanente e encerrar a run? Exporte o TXT antes para recuperar depois.')){meta=fresh();persist();newRun();menu()}}}
function almanac(){const mult=BALANCE.plantCostScaling.defaultMultiplier;show('<small>GARDEN ALMANAC</small><h2>Espécies do jardim</h2><p>Cada cópia viva torna a próxima unidade da mesma espécie mais cara. Espécies diferentes não se afetam.</p><div class="almanac-list">'+PLANTS.map(p=>{const m=p.costGrowth??mult;return '<div class="meta-row"><div><b>'+p.name+'</b><br><span>'+p.description+'</span></div><div class="almanac-cost"><b>'+p.baseCost+' Sun</b><span>+'+Math.round((m-1)*100)+'% por cópia<br>'+p.baseCost+' → '+Math.round(p.baseCost*m)+' → '+Math.round(p.baseCost*m*m)+'</span></div></div>'}).join('')+'</div><button id="back">Voltar</button>');$('back').onclick=menu}
function metaMenu(){show('<small>MELHORIAS PERMANENTES</small><h2>'+meta.seeds+' Seeds</h2><p>Afetam a próxima run. Limite: nível 10.</p>'+[['mastery','Peashooter Mastery / Arsenal','+2% de dano de todas as plantas por nível'],['economy','Starting Sun','+10 Sun iniciais por nível'],['fortress','Base HP','+5% de vida inicial da base por nível']].map(([k,n,d])=>'<div class="meta-row"><div><b>'+n+' · '+meta[k]+'/10</b><br><span>'+d+'</span></div><button data-buy="'+k+'" '+(meta[k]>=10||meta.seeds<10+meta[k]*8?'disabled':'')+'>'+(meta[k]>=10?'MAX':10+meta[k]*8+' Seeds')+'</button></div>').join('')+'<button id="back">Voltar</button>');$('back').onclick=menu;document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const k=b.dataset.buy,c=10+meta[k]*8;if(meta.seeds>=c&&meta[k]<10){meta.seeds-=c;meta[k]++;persist();metaMenu()}})}
$('import').onchange=async e=>{const f=e.target.files[0];try{if(!f)return;if(f.size>100000)throw Error('Arquivo grande demais.');const incoming=validate(JSON.parse(await f.text()));if(confirm('Substituir o progresso atual por este save e reiniciar a run?')){meta=incoming;persist();newRun();menu();toast('Save importado.')}}catch(err){toast('Não foi possível importar: '+err.message)}finally{e.target.value=''}};
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_garden_run',description:'Lê o estado atual da run sem alterar o jogo.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('Nenhum parâmetro esperado.');return {state:g.state,wave:g.wave,sun:g.sun,plantFood:g.food,baseHp:g.hp,kills:g.kills}}},{signal:lifecycle.signal})).catch(()=>{});addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}
if(BALANCE.debug){window.gardenDebug={sun:()=>g.sun+=1000,food:()=>g.food+=10,kill:()=>g.zombies.forEach(z=>g.damage(z,z.hp)),next:()=>g.startWave(),damage:()=>g.hp=0,seeds:()=>{meta.seeds+=100;persist()}}}
let uiTick=0;function loop(now){const dt=Math.min((now-last)/1000,.1);last=now;acc+=dt*g.speed;while(acc>=1/60){g.step(1/60);acc-=1/60}render(ctx,g,selected,hover,inspected);uiTick+=dt;if(g.plantRevision!==lastPlantRevision){lastPlantRevision=g.plantRevision;update();uiTick=0}else if(uiTick>.2){uiTick=0;update()}requestAnimationFrame(loop)}update();menu();requestAnimationFrame(loop);
