import {Game} from './game.js';
import {render,plantImage} from './render.js';
import {PLANTS,BALANCE as B,CLASSES,METRICS} from './data.js';
import {PLANT_LEVELS} from './plantUpgrades.js';
import {UPGRADES,RARITIES,affects} from './roguelikeUpgrades.js';
import {read,write,validate,download,fresh} from './save.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),modal=$('modal');
const images=Object.fromEntries(PLANTS.map(p=>[p.id,plantImage(p.id)]));
let meta=read(),selected='peashooter',hover=null,inspected=null,last=performance.now(),acc=0,toastTimer,screen='menu',started=false,inspectionKey='',cardsKey='',pickupsKey='';
const fmt=n=>Number.isFinite(n)?Number(n.toFixed(1)).toLocaleString('pt-BR'):'—';
const clock=t=>Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');
const iconPaths={play:'M8 5l12 7-12 7z',plants:'M12 21V10M12 14C3 15 3 7 3 4c7 0 10 4 9 10M12 10c0-5 4-7 9-7 0 6-3 10-9 10',upgrades:'M12 21V4M5 11l7-7 7 7',stats:'M5 20V12M12 20V4M19 20V8',save:'M5 3h13l3 3v15H3V3zM7 3v6h10V3M7 21v-8h10v8',settings:'M12 3v3M12 18v3M3 12h3M18 12h3M6 6l2 2M16 16l2 2M6 18l2-2M16 8l2-2M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0'};
const icon=k=>'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="'+iconPaths[k]+'"/></svg>';
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800)}
function persist(){const ok=write(meta);if(!ok)toast('Não foi possível salvar. Exporte o TXT para guardar seu progresso.');return ok}
function show(html,name){screen=name;$('modal-content').innerHTML=html;if(!modal.open)modal.showModal()}
function close(){modal.close();screen='game';g.paused=false;last=performance.now();acc=0;inspectionKey='';update()}
function title(name,back=menu){return '<div class="dialog-top"><h2 id="dialog-title">'+name+'</h2><button id="back">Voltar</button></div>'}
function bindBack(fn=menu){$('back').onclick=fn}
function targetName(target){return PLANTS.find(p=>p.id===target)?.name||CLASSES[target.replace('class:','')]||({global:'Todas as plantas',economy:'Economia',base:'Jardim'}[target])||target}
const metricLabels={sunSpawned:'Sun gerado',sunCollected:'Sun coletado',sunMissed:'Sun perdido',sunflowerSun:'Sun de Sunflowers',naturalSun:'Sun natural',plantsPlaced:'Plantas colocadas',plantsLost:'Plantas perdidas',damageDealt:'Dano causado'};
const g=new Game(meta,onWave,onEnd);
function newRun(){g.meta=meta;g.reset();selected='peashooter';inspected=null;started=true;close();toast('Prepare sua defesa. Os Suns aparecem somente durante o combate.')}
function onEnd(){const record=g.wave>meta.highestWave;meta.seeds+=g.earned;meta.highestWave=Math.max(meta.highestWave,g.wave);meta.totalRuns++;meta.kills+=g.kills;meta.time+=Math.floor(g.combatTime);for(const k of METRICS)meta.statistics[k]+=Math.floor(g.metrics[k]);persist();show('<small>'+(record?'NOVO RECORDE!':'FIM DA RUN')+'</small><h2 id="dialog-title">Uma nova chance de florescer.</h2><div class="metric-grid">'+[['Wave',g.wave],['Zumbis',g.kills],['Tempo de combate',clock(g.combatTime)],['Sun coletado',g.metrics.sunCollected],['Plantas',g.placed],['Seeds ganhos','+'+g.earned]].map(([k,v])=>'<div>'+k+'<b>'+v+'</b></div>').join('')+'</div><div class="save-actions"><button class="primary" id="again">Jogar novamente</button><button id="return">Voltar ao jardim</button></div>','over');$('again').onclick=newRun;$('return').onclick=menu;update()}
function preview(u){if(u.target==='base')return u.id==='foundation'?'HP máximo: '+fmt(g.maxHp)+' → '+fmt(g.maxHp*1.12):'HP: '+fmt(g.hp)+' → '+fmt(Math.min(g.maxHp,g.hp+g.maxHp*.2));if(u.target==='economy')return 'Valor dos pickups ×1,10';const p=PLANTS.find(p=>affects(u,p));if(!p)return '';const a=g.stats(p),b=g.stats(p,{extra:u}),key=u.effects[0].stat;return targetName(p.id)+': '+(key==='costDiscount'?fmt(a.costDiscount*100)+'% → '+fmt(b.costDiscount*100)+'% de desconto':fmt(a[key]||0)+' → '+fmt(b[key]||0))}
function onWave(choices){show('<small>WAVE '+g.wave+' CONCLUÍDA · +1 PLANT FOOD</small><h2 id="dialog-title">Escolha como crescer.</h2><p>Um upgrade para esta run. Os efeitos acumulam até seus limites.</p><div class="choices">'+choices.map(u=>{const plant=PLANTS.find(p=>affects(u,p));return '<button class="choice" data-upgrade="'+u.id+'"><span class="rarity '+u.rarity+'">'+RARITIES[u.rarity].label+'</span>'+(plant?'<img alt="" src="'+images[plant.id]+'">':'')+'<span class="target">'+targetName(u.target)+'</span><strong>'+u.name+'</strong><p>'+u.desc+'</p><span class="before">'+preview(u)+'</span></button>'}).join('')+'</div>','upgrade');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{if(g.upgrade(b.dataset.upgrade)){inspectionKey='';close()}})}
function menu(){g.paused=true;show('<div class="main-menu"><div class="menu-art">'+['sunflower','peashooter','wallNut','repeater'].map(id=>'<img alt="" src="'+images[id]+'">').join('')+'</div><h2 id="dialog-title">Garden<span>LAST STAND</span></h2><p>Defenda seu jardim. Colete Sun. Faça sua build florescer.</p><button class="primary play" id="play">'+icon('play')+' '+(started&&g.state!=='over'?'Continuar run':'Jogar')+'</button><div class="menu-grid"><button id="almanac">'+icon('plants')+'Plantas</button><button id="meta">'+icon('upgrades')+'Melhorias</button><button id="stats">'+icon('stats')+'Estatísticas</button><button id="save-menu">'+icon('save')+'Save</button></div><button id="settings" style="margin-top:15px">'+icon('settings')+' Configurações</button><p><small>Recorde: wave '+meta.highestWave+' · '+meta.seeds+' Seeds</small></p></div>','menu');$('play').onclick=()=>{if(!started||g.state==='over')newRun();else if(g.state==='upgrade')onWave(g.choices);else close()};$('almanac').onclick=()=>almanac();$('meta').onclick=metaMenu;$('stats').onclick=statistics;$('save-menu').onclick=saveMenu;$('settings').onclick=settings;update()}
function settings(){show(title('Configurações')+'<label class="setting"><span><b>Iniciar waves automaticamente</b><br><small>15s antes da primeira; 9s entre waves. A pausa congela a contagem.</small></span><input type="checkbox" id="auto" '+(meta.settings.autoStart?'checked':'')+'></label><p>Atalhos: 1–7 selecionam plantas, espaço pausa, Esc cancela a seleção. Clique nos Suns amarelos para coletar.</p>','settings');bindBack();$('auto').onchange=()=>{meta.settings.autoStart=$('auto').checked;g.autoStart=meta.settings.autoStart;persist();update()}}
function saveMenu(){show(title('Seu progresso')+'<p>Masteries, Seeds e estatísticas são salvos neste navegador. A run em andamento não é salva. Saves TXT antigos também são aceitos.</p><div class="save-actions"><button id="save">Salvar agora</button><button id="export">Exportar TXT</button><button id="import-btn">Importar TXT</button></div><button class="danger" id="reset">Resetar progresso</button>','save');bindBack();$('save').onclick=()=>{if(persist())toast('Progresso permanente salvo.')};$('export').onclick=()=>download(meta);$('import-btn').onclick=()=>$('import').click();$('reset').onclick=()=>{show(title('Resetar progresso',saveMenu)+'<p>Todos os Seeds, masteries e estatísticas serão apagados. Exporte um TXT antes para poder recuperá-los.</p><button id="confirm-reset" class="danger">Confirmar reset</button>','reset');bindBack(saveMenu);$('confirm-reset').onclick=()=>{meta=fresh();persist();started=false;g.meta=meta;g.reset();menu()}}}
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>100000)throw Error('Arquivo grande demais.');const incoming=validate(JSON.parse(await f.text()));show(title('Importar progresso',saveMenu)+'<p>Substituir o progresso atual por '+incoming.seeds+' Seeds e recorde de wave '+incoming.highestWave+'? A run atual será encerrada.</p><button class="primary" id="confirm-import">Confirmar importação</button>','import');bindBack(saveMenu);$('confirm-import').onclick=()=>{meta=incoming;persist();g.meta=meta;g.reset();started=false;menu();toast('Save importado e atualizado para versão 2.')}}catch(err){toast('Importação recusada: '+err.message)}finally{e.target.value=''}};
function statistics(){show(title('Estatísticas')+'<div class="metric-grid">'+[['Recorde',meta.highestWave],['Runs',meta.totalRuns],['Zumbis',meta.kills],['Combate',clock(meta.time)],['Seeds',meta.seeds],...METRICS.map(k=>[metricLabels[k],meta.statistics[k]])].map(([k,v])=>'<div>'+k+'<b>'+fmtOrText(v)+'</b></div>').join('')+'</div>','statistics');bindBack()}
function fmtOrText(v){return typeof v==='number'?fmt(v):v}
function metaMenu(){show(title('Melhorias permanentes')+'<p><b>'+meta.seeds+' Seeds</b> · Aplicadas na próxima run.</p>'+PLANTS.map(p=>'<div class="meta-row"><div><b>'+p.name+' · '+meta.plantMastery[p.id]+'/10</b><small>'+masteryText(p)+'</small></div><button data-mastery="'+p.id+'" '+(meta.plantMastery[p.id]>=10||meta.seeds<10+meta.plantMastery[p.id]*8?'disabled':'')+'>'+ (meta.plantMastery[p.id]>=10?'Máximo':10+meta.plantMastery[p.id]*8+' Seeds')+'</button></div>').join('')+[['economy','Starting Sun','+10 Sun inicial por nível'],['fortress','Base HP','+5% HP do jardim por nível']].map(([k,n,d])=>'<div class="meta-row"><div><b>'+n+' · '+meta[k]+'/10</b><small>'+d+'</small></div><button data-global="'+k+'" '+(meta[k]>=10||meta.seeds<10+meta[k]*8?'disabled':'')+'>'+(meta[k]>=10?'Máximo':10+meta[k]*8+' Seeds')+'</button></div>').join(''),'meta');bindBack();document.querySelectorAll('[data-mastery]').forEach(b=>b.onclick=()=>buy(meta.plantMastery,b.dataset.mastery));document.querySelectorAll('[data-global]').forEach(b=>b.onclick=()=>buy(meta,b.dataset.global))}
function buy(obj,key){const cost=10+obj[key]*8;if(obj[key]<10&&meta.seeds>=cost){meta.seeds-=cost;obj[key]++;persist();metaMenu()}}
function masteryText(p){return p.id==='wallNut'?'+3% HP por nível':p.id==='sunflower'?'+2% Sun por nível':p.id==='potatoMine'?'+3% dano por nível':'+2% dano por nível'}
function almanac(filter='all'){show(title('Garden Almanac')+'<div class="tabs">'+Object.entries(CLASSES).map(([id,n])=>'<button data-class="'+id+'" class="'+(filter===id?'active':'')+'">'+n+'</button>').join('')+'</div><div class="collection">'+PLANTS.filter(p=>filter==='all'||p.class===filter).map(p=>'<button data-detail="'+p.id+'"><img alt="" src="'+images[p.id]+'"><b>'+p.name+'</b><small>'+CLASSES[p.class]+'</small><strong>'+p.baseCost+' Sun</strong><small>Mastery '+meta.plantMastery[p.id]+'/10</small><p>'+p.role+'</p></button>').join('')+'</div>','almanac');bindBack();document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>almanac(b.dataset.class));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>plantDetail(b.dataset.detail,filter))}
const statNames={hp:'HP máximo',damage:'Dano',attackInterval:'Intervalo de ataque (s)',dps:'DPS médio estimado',range:'Alcance (tiles)',projectileCount:'Projéteis',projectileSpeed:'Velocidade do projétil',splashRadius:'Raio da área',productionInterval:'Produção (s)',sunAmount:'Sun por pickup',armTime:'Tempo para armar (s)',damageReduction:'Redução de dano',regen:'Cura entre waves',thorns:'Dano de espinhos',extraChance:'Chance de ervilha extra',doubleSunChance:'Chance de Sun duplo',criticalChance:'Chance crítica'};
const shownStats=s=>Object.keys(statNames).filter(k=>s[k]!==undefined&&(s[k]>0||k==='hp'));
const statValue=(s,k)=>['damageReduction','regen','extraChance','doubleSunChance','criticalChance'].includes(k)?fmt(s[k]*100)+'%':fmt(s[k]);
function plantDetail(id,filter){const p=PLANTS.find(p=>p.id===id),s=g.stats(p,{permanent:true}),base={...p,dps:p.attackInterval?p.damage*(p.projectileCount||1)/p.attackInterval:0};show(title(p.name,()=>almanac(filter))+'<div class="plant-detail-head"><img alt="'+p.name+'" src="'+images[id]+'"><div><b>'+CLASSES[p.class]+' · Mastery '+meta.plantMastery[id]+'/10</b><p>'+p.role+'</p><small>'+masteryText(p)+'</small></div></div><p><b>'+p.abilityName+'</b><br>'+p.description+'</p><p>Custo base <b>'+p.baseCost+' Sun</b> · +'+fmt(((p.costGrowth??B.plantCostScaling.defaultMultiplier)-1)*100)+'% por cópia viva<br>Primeiras unidades: '+[0,1,2].map(count=>g.getPlantCost(id,{count,discount:false})).join(' → ')+' Sun</p><table class="stat-table"><thead><tr><th>ATRIBUTO</th><th>BASE</th><th>COM MASTERY</th></tr></thead><tbody>'+shownStats(s).map(k=>'<tr><td>'+statNames[k]+'</td><td>'+statValue(base,k)+'</td><td>'+statValue(s,k)+'</td></tr>').join('')+'</tbody></table><h3>Plant Food · evolução da run</h3><p>Começa no nível 1 a cada run. '+(started?'Nesta run: nível '+g.levels[id]+'.':'')+'</p><div class="food-levels"><div><b>LV 1</b> · Forma base</div>'+PLANT_LEVELS[id].map((l,i)=>'<div><b>LV '+(i+2)+' · '+B.plantFoodUpgradeCosts[i]+' Plant Food</b><br>'+l.desc+'</div>').join('')+'</div>','detail');bindBack(()=>almanac(filter))}
function buildView(){g.paused=true;const counts={};g.upgrades.forEach(id=>counts[id]=(counts[id]||0)+1);show(title('Sua build',close)+(g.upgrades.length?'':'<p>Complete uma wave para escolher seu primeiro upgrade.</p>')+Object.entries(counts).map(([id,n])=>{const u=UPGRADES.find(u=>u.id===id),e=u.effects[0];const total=e.mode==='multiply'?(e.stat==='attackInterval'||e.stat==='productionInterval'?fmt((1/Math.pow(e.value,n)-1)*100)+'% mais rápido':fmt((Math.pow(e.value,n)-1)*100)+'%'):e.mode==='add'?fmt(e.value*n):e.value;return '<div class="build-item"><span class="rarity '+u.rarity+'">'+RARITIES[u.rarity].label+'</span><strong>'+u.name+' ×'+n+'</strong><p>'+targetName(u.target)+' · '+u.desc+'</p><small>Total deste upgrade: '+total+' · sujeito aos caps</small></div>'}).join('')+'<p>Limites: ataque ≥0,18s · produção ≥4s · alcance ≤8 · chances ≤60% · desconto ≤25%. Os stats de cada planta refletem os limites.</p>','build');bindBack(close)}

$('plants').innerHTML=PLANTS.map((p,i)=>'<button class="plant-card" data-plant="'+p.id+'" aria-label="Selecionar '+p.name+'"><span class="hotkey">'+(i+1)+'</span><span class="evolvable" hidden>↑ LV</span><img alt="" src="'+images[p.id]+'"><span class="name">'+p.name+'</span><span class="cost"></span><span class="field-count"></span></button>').join('');
document.querySelectorAll('[data-plant]').forEach(b=>b.onclick=()=>{selected=b.dataset.plant;inspected=null;inspectionKey='';update()});
function flySun(drop){const r=canvas.getBoundingClientRect(),to=$('sun').getBoundingClientRect(),el=document.createElement('div');el.className='sun-flight';el.style.left=(r.left+drop.x/20*r.width-12)+'px';el.style.top=(r.top+drop.y/14*r.height-12)+'px';document.body.append(el);requestAnimationFrame(()=>{el.style.transform='translate('+(to.left-r.left-drop.x/20*r.width)+'px,'+(to.top-r.top-drop.y/14*r.height)+'px) scale(.3)';el.style.opacity='0'});setTimeout(()=>el.remove(),550)}
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();hover={x:(e.clientX-r.left)/r.width*20,y:(e.clientY-r.top)/r.height*14}});canvas.addEventListener('pointerleave',()=>hover=null);
canvas.addEventListener('click',e=>{if(modal.open||g.paused)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*20,y=(e.clientY-r.top)/r.height*14,drop=g.sunDrops.find(s=>Math.hypot(s.x-x,s.y-y)<=B.pickupRadius),result=g.clickMap(x,y,selected);if(result==='sun'&&drop)flySun(drop);else if(typeof result==='object'&&result){inspected=result;selected=null}else if(!result&&selected)toast('Sun insuficiente ou tile indisponível.');inspectionKey='';update()});
$('next').onclick=()=>{g.startWave();update()};$('pause').onclick=()=>{if(!modal.open&&started&&g.state!=='over'){g.paused=!g.paused;last=performance.now();update()}};$('speed').onclick=()=>{g.speed=g.speed%3+1;update()};$('menu').onclick=menu;$('build').onclick=buildView;
document.addEventListener('keydown',e=>{if(modal.open||e.target.matches('input'))return;if(e.code==='Space'){e.preventDefault();$('pause').click()}if(e.key==='Escape'){selected=null;inspected=null}if(/^[1-7]$/.test(e.key)){selected=PLANTS[Number(e.key)-1].id;inspected=null}inspectionKey='';update()});
modal.addEventListener('cancel',e=>{e.preventDefault();if(screen==='upgrade'||screen==='over'||screen==='menu')return;menu()});
document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden&&started){g.paused=true;update()}});

function update(){
 for(const [id,value] of Object.entries({wave:Math.max(1,g.wave),sun:Math.floor(g.sun),food:g.food,hp:Math.ceil(g.hp)+' / '+Math.ceil(g.maxHp),enemies:g.zombies.length+g.queue,kills:g.kills,time:clock(g.combatTime),record:meta.highestWave}))$(id).textContent=value;
 $('health').max=g.maxHp;$('health').value=g.hp;$('pause').textContent=g.paused?'Retomar':'Pausar';$('speed').textContent=g.speed+'×';$('next').disabled=g.state!=='intermission'||g.paused;$('next').textContent=g.state==='intermission'?'Começar wave '+(g.wave+1)+' agora':'Wave '+g.wave+' em andamento';
 $('countdown').textContent=g.state==='intermission'?(g.autoStart?'Próxima wave em '+Math.ceil(g.countdown)+'s':'Preparação · início manual'):g.state==='playing'?'Proteja o jardim!':'Wave encerrada';const nextWave=g.state==='intermission'?g.wave+1:g.wave;$('status').textContent=g.paused?'Pausado':(nextWave<=2?'Inimigos pelo norte':nextWave<=4?'Inimigos pelo norte e sul':'Inimigos por todos os lados')+(g.state==='intermission'?' · preparação':' · colete Sun');
 const ck=[g.sun,g.food,selected,g.plantRevision,g.upgrades.length,...PLANTS.map(p=>g.fieldCount(p.id))].join('|');
 if(ck!==cardsKey){cardsKey=ck;document.querySelectorAll('[data-plant]').forEach(b=>{const p=PLANTS.find(p=>p.id===b.dataset.plant),s=g.stats(p),n=g.fieldCount(p.id),cost=g.getPlantCost(p.id),c=b.querySelector('.cost');if(b.dataset.lastCost&&Number(b.dataset.lastCost)!==cost){c.classList.remove('cost-flash');void c.offsetWidth;c.classList.add('cost-flash')}b.dataset.lastCost=cost;b.classList.toggle('selected',selected===p.id);b.setAttribute('aria-disabled',String(g.sun<cost));c.textContent=cost+' Sun';b.querySelector('.field-count').textContent=n?'×'+n+' no campo':'';b.querySelector('.evolvable').hidden=g.food<g.foodCost(p.id);b.title=p.name+' · '+CLASSES[p.class]+'\n'+p.role+'\nBase: '+p.baseCost+' Sun · No campo: '+n+'\nPróxima: '+cost+' Sun · +20% por cópia\nHP: '+fmt(s.hp)+(s.damage?' · Dano: '+fmt(s.damage):'')+(s.sunAmount?' · Sun: '+fmt(s.sunAmount)+' / '+fmt(s.productionInterval)+'s':'')+'\n'+p.abilityName+': '+p.description})}
 const pk=g.sunDrops.map(s=>s.id).join(',');if(pk!==pickupsKey){pickupsKey=pk;$('pickup-controls').innerHTML=g.sunDrops.map(s=>'<button class="pickup-button" data-sun="'+s.id+'" aria-label="Coletar '+s.amount+' Sun" style="left:'+s.x/20*100+'%;top:'+s.y/14*100+'%"></button>').join('');document.querySelectorAll('[data-sun]').forEach(b=>b.onclick=()=>{const s=g.collectSun(Number(b.dataset.sun));if(s)flySun(s);update()})}
 const p=inspected&&g.plants.includes(inspected)?inspected:PLANTS.find(p=>p.id===selected),key=[p?.id,p?.uid,g.levels[p?.id],g.upgrades.length,g.food,g.plantRevision,g.paused].join('|');
 if(key!==inspectionKey){inspectionKey=key;if(!p)$('inspect').innerHTML='<h2>Seu jardim, sua estratégia.</h2><p>Selecione uma planta para ver atributos e a próxima evolução.</p>';else{const s=g.stats(p),lv=g.levels[p.id],cost=g.foodCost(p.id);$('inspect').innerHTML='<div class="inspect-head"><img alt="" src="'+images[p.id]+'"><h2>'+p.name+'<small>'+CLASSES[p.class]+' · LV '+lv+'</small></h2></div><p><b>'+p.abilityName+'</b> · '+p.description+'</p><div class="compact-stats"><span>HP<b id="plant-hp"></b></span>'+ (s.attackInterval?'<span>Dano / DPS<b>'+fmt(s.damage)+' / '+fmt(s.dps)+'</b></span><span>Intervalo<b>'+fmt(s.attackInterval)+'s</b></span><span>Alcance<b>'+fmt(s.range)+'</b></span>':s.productionInterval?'<span>Sun por pickup<b>'+fmt(s.sunAmount)+'</b></span><span>Produção<b>'+fmt(s.productionInterval)+'s</b></span><span>Próximo Sun<b id="production-next"></b></span>':s.armTime?'<span>Dano / área<b>'+fmt(s.damage)+' / '+fmt(s.splashRadius)+'</b></span><span>Arma em<b id="arm-next"></b></span>':'<span>Redução / cura<b>'+fmt(s.damageReduction*100)+'% / '+fmt(s.regen*100)+'%</b></span>')+'</div><div class="evolve-detail"><strong>'+(lv<5?'LV '+lv+' → LV '+(lv+1):'Nível máximo')+'</strong><p>'+(PLANT_LEVELS[p.id][lv-1]?.desc||'Todas as evoluções desta espécie foram desbloqueadas.')+'</p><button id="feed" '+(g.food<cost||g.paused?'disabled':'')+' class="'+(g.food<cost?'insufficient':'primary')+'">'+(lv>=5?'LV 5 / 5':'Evoluir · '+cost+' Plant Food')+'</button></div>';$('feed').onclick=()=>{if(g.plantFood(p.id)){inspectionKey='';toast('Evolução aplicada a esta espécie na run.');update()}}}}
 if(p&&$('plant-hp')){$('plant-hp').textContent=inspected&&g.plants.includes(inspected)?fmt(inspected.hp)+' / '+fmt(inspected.maxHp):fmt(g.stats(p).hp);if($('production-next'))$('production-next').textContent=fmt(g.stats(p).productionInterval-(inspected?.productionTimer||0))+'s';if($('arm-next'))$('arm-next').textContent=fmt(Math.max(0,g.stats(p).armTime-(inspected?.age||0)))+'s'}
 $('upgrades').innerHTML=g.upgrades.slice(-3).reverse().map(id=>{const u=UPGRADES.find(u=>u.id===id);return '<div class="upgrade-line"><span class="rarity '+u.rarity+'">'+RARITIES[u.rarity].label+'</span>'+u.name+'</div>'}).join('')||'<p>Complete waves e escolha sua build.</p>';
}
if(B.debug){const panel=document.createElement('div');panel.className='debug';document.querySelector('aside').append(panel);const actions={'+1000 Sun':()=>g.sun+=1000,'+10 Food':()=>g.food+=10,'Kill zombies':()=>{g.queue=0;g.zombies.forEach(z=>g.damage(z,z.hp))},'Next wave':()=>g.startWave(),'Damage base':()=>g.hp=0,'+100 Seeds':()=>{meta.seeds+=100;persist()}};for(const [name,fn] of Object.entries(actions)){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{fn();update()};panel.append(b)}}
// Fixed simulation step: all speeds use the same combat/production rules.
let tick=0,lastRevision=-1;function loop(now){const dt=Math.min((now-last)/1000,.1);last=now;acc+=dt*g.speed;while(acc>=1/60){g.step(1/60);acc-=1/60}render(ctx,g,selected,hover,inspected);tick+=dt;if(tick>.1||g.plantRevision!==lastRevision||pickupsKey!==g.sunDrops.map(s=>s.id).join(',')){lastRevision=g.plantRevision;tick=0;update()}requestAnimationFrame(loop)}
update();menu();requestAnimationFrame(loop);
