const effect=(stat,value,mode='multiply')=>({stat,value,mode});
const u=(id,name,target,desc,stat,value,rarity='common',mode='multiply',maxStacks=5)=>({id,name,target,desc,rarity,maxStacks,effects:[effect(stat,value,mode)]});
export const UPGRADES=[
 u('sharp','Sharpened Peas','peashooter','+20% dano','damage',1.2),u('rapid','Rapid Peas','peashooter','+15% velocidade de ataque','attackInterval',1/1.15),u('stem','Long Stem','peashooter','+15% alcance','range',1.15),u('double','Double Trouble','peashooter','+20% chance de ervilha extra','extraChance',.2,'rare','add',3),u('caliber','Green Caliber','peashooter','+6 dano por ervilha','damage',6,'common','add'),
 u('twin','Twin Barrels','repeater','+15% dano','damage',1.15),u('suppress','Suppressive Fire','repeater','+15% velocidade de ataque','attackInterval',1/1.15),u('triple','Triple Burst','repeater','3º ataque dispara ervilha extra','burstEvery',3,'epic','set',1),u('barrel','Long Barrel','repeater','+12% alcance','range',1.12),u('overdrive','Overdrive','repeater','+22% velocidade de ataque','attackInterval',1/1.22,'rare'),
 u('bigSun','Big Sun','sunflower','+5 Sun por pickup','sunAmount',5,'common','add'),u('photo','Photosynthesis','sunflower','Produção 15% mais rápida','productionInterval',1/1.15),u('golden','Golden Bloom','sunflower','+15% chance de dois Suns','doubleSunChance',.15,'rare','add',4),u('deep','Deep Roots','sunflower','+40% HP','hp',1.4),u('network','Solar Network','sunflower','+5% produção por Sunflower; máx. +25%','network',.05,'rare','set',1),
 u('hands','Heavy Hands','bonkChoy','+25% dano','damage',1.25),u('frenzy','Frenzy','bonkChoy','+15% velocidade de ataque','attackInterval',1/1.15),u('reach','Long Reach','bonkChoy','+0,25 alcance','range',.25,'common','add'),{...u('combo','Combo Punch','bonkChoy','5º soco causa 2× dano em área','comboEvery',5,'epic','set',1),effects:[effect('comboEvery',5,'set'),effect('comboMultiplier',2,'set'),effect('comboRadius',1,'set')]},u('spirit','Fighting Spirit','bonkChoy','+8% dano por inimigo próximo; máx. +32%','crowdBonus',.08,'rare','set',1),
 u('heavy','Heavy Cabbage','cabbagePult','+25% dano','damage',1.25),u('splash','Bigger Splash','cabbagePult','+25% raio de impacto','splashRadius',1.25),u('lob','Fast Lob','cabbagePult','+15% velocidade de ataque','attackInterval',1/1.15),u('arc','Crushing Arc','cabbagePult','+20% chance de crítico de 1,75×','criticalChance',.2,'rare','add',3),u('artRange','Artillery Range','cabbagePult','+15% alcance','range',1.15),
 u('nitro','Nitro Potato','potatoMine','+30% dano de explosão','damage',1.3),u('fuse','Fast Fuse','potatoMine','Tempo para armar −20%','armTime',.8),u('boom','Big Boom','potatoMine','+25% raio de explosão','splashRadius',1.25),u('cheap','Cheap Explosives','potatoMine','−10% custo; limite total 25%','costDiscount',.1,'common','add',3),u('charge','Packed Charge','potatoMine','+45% dano; carga reforçada','damage',1.45,'epic'),
 u('shell','Hard Shell','wallNut','+30% HP','hp',1.3),u('reinforce','Reinforced Shell','wallNut','+8% redução de dano','damageReduction',.08,'rare','add',5),u('repair','Self Repair','wallNut','Recupera 5% HP por wave','regen',.05,'rare','add',3),u('thorns','Thorns','wallNut','Retorna 12 dano por ataque recebido','thorns',12,'rare','add',5),u('bigger','Bigger Nut','wallNut','+45% HP; mesmo tamanho','hp',1.45,'epic'),
 u('arsenal','Garden Arsenal','global','+8% dano ofensivo','damage',1.08),u('tough','Tough Roots','global','+10% HP','hp',1.1),u('growth','Rapid Growth','global','+8% velocidade de ataque','attackInterval',1/1.08),u('fertile','Fertile Ground','global','+8% alcance','range',1.08),u('sunny','Sunny Day','economy','+10% valor de todos os Suns','sunValue',1.1),u('emergency','Emergency Repairs','base','Recupera 20% da base','heal',.2,'common','add',99),u('foundation','Strong Foundation','base','+12% HP máximo e cura o adicional','baseHp',1.12),u('frugal','Frugal Planting','global','−5% custo; limite total 25%','costDiscount',.05,'rare','add',5),
 u('shooters','Pea Alliance','class:shooter','+12% dano das atiradoras','damage',1.12),u('meleeClass','Close Quarters','class:melee','+20% HP corpo a corpo','hp',1.2),u('trapClass','Prepared Ground','class:trap','Armadilhas armam 15% mais rápido','armTime',.85)
];
export const RARITIES={common:{label:'Comum',weight:60},rare:{label:'Raro',weight:30},epic:{label:'Épico',weight:10}};
export function affects(u,p){return u.target==='global'||u.target===p.id||u.target==='class:'+p.class}
export function chooseUpgrades(game,rng=Math.random){
 let pool=UPGRADES.filter(u=>game.upgrades.filter(id=>id===u.id).length<u.maxStacks);const chosen=[];
 function pick(candidates){if(!candidates.length)return;const tiers=Object.keys(RARITIES).filter(r=>candidates.some(u=>u.rarity===r));let n=rng()*tiers.reduce((a,r)=>a+RARITIES[r].weight,0),tier=tiers.at(-1);for(const r of tiers){n-=RARITIES[r].weight;if(n<0){tier=r;break}}const items=candidates.filter(u=>u.rarity===tier),u=items[Math.min(items.length-1,Math.floor(rng()*items.length))];chosen.push(u);pool=pool.filter(v=>v.id!==u.id)}
 pick(pool.filter(u=>game.plants.some(p=>p.hp>0&&u.target!=='global'&&affects(u,p))));pick(pool.filter(u=>['global','economy','base'].includes(u.target)));while(chosen.length<3&&pool.length)pick(pool);return chosen;
}
