import assert from 'node:assert/strict';
import {Game} from '../dist/js/game.js';
import {fresh,validate,migrateSaveV1ToV2,read,write} from '../dist/js/save.js';
import {PLANTS,BALANCE as B} from '../dist/js/data.js';
import {UPGRADES,chooseUpgrades} from '../dist/js/roguelikeUpgrades.js';
let tests=0;const test=(name,fn)=>{fn();tests++;console.log('PASS',name)};
const make=()=>new Game(fresh());
function seconds(g,n){for(let i=0;i<n*60;i++)g.step(1/60)}
function active(){const g=make();g.startWave();g.queue=0;g.zombies=[{x:.5,y:.5,hp:1e9,maxHp:1e9,speed:0,damage:0,cool:0,flash:0,uid:999}];return g}
function take(g,id){const u=UPGRADES.find(u=>u.id===id);g.state='upgrade';g.choices=[u];assert(g.upgrade(u))}
test('placement bounds, occupancy and exact debit',()=>{const g=make();assert(!g.place('peashooter',0,2));assert(!g.place('peashooter',9,6));const cost=g.getPlantCost('peashooter'),before=g.sun;assert(g.place('peashooter',8,5));assert.equal(before-g.sun,cost);assert(!g.place('sunflower',8,5));g.sun=0;assert(!g.place('peashooter',7,5))});
test('progressive cost 50/60/72/86 and species independence',()=>{const g=make(),p=PLANTS.find(p=>p.id==='sunflower'),old=p.baseCost;p.baseCost=50;try{g.sun=10000;for(const [i,c] of [50,60,72,86].entries()){assert.equal(g.getPlantCost(p.id),c);assert(g.place(p.id,2+i,2))}assert(g.place('peashooter',7,2));assert.equal(g.getPlantCost(p.id),104);assert.equal(g.getPlantCost('wallNut'),100);g.plants[0].hp=0;assert.equal(g.getPlantCost(p.id),86);g.cleanupPlants();assert.equal(g.getPlantCost(p.id),86)}finally{p.baseCost=old}});
test('scaling then discount with a single final rounding and cap',()=>{const g=make();g.sun=10000;g.place('peashooter',2,2);g.place('peashooter',3,2);g.mods.costDiscount=.1;assert.equal(g.getPlantCost('peashooter'),130);g.mods.costDiscount=.9;assert.equal(g.getPlantCost('peashooter'),108)});
test('pre-wave 60s never generates Sun, timers or combat time (auto off)',()=>{const g=make();g.autoStart=false;g.place('sunflower',3,3);const s=g.sun;seconds(g,60);assert.equal(g.sun,s);assert.equal(g.combatTime,0);assert.equal(g.sunDrops.length,0);assert.equal(g.plants[0].productionTimer,0);assert.equal(g.intermissionTime>59,true)});
test('auto countdown, start now and pause',()=>{const g=make();g.paused=true;seconds(g,30);assert.equal(g.countdown,15);g.paused=false;seconds(g,15.1);assert.equal(g.state,'playing');assert.equal(g.wave,1);assert(!g.startWave());const h=make();assert(h.startWave());assert.equal(h.wave,1)});
test('natural Sun is pickup, click collects only once, expiry counted',()=>{const g=active(),balance=g.sun;seconds(g,10.1);assert.equal(g.sun,balance);assert.equal(g.sunDrops.length,1);const s=g.sunDrops[0];assert.equal(g.clickMap(s.x,s.y,'peashooter'),'sun');assert.equal(g.plants.length,0);assert.equal(g.sun,balance+15);assert(!g.collectSun(s.id));g.spawnSun('natural',3,3,15);seconds(g,12.1);assert(g.metrics.sunMissed>=15)});
test('Sunflower pickup only and pause freezes all timers',()=>{const g=active();g.place('sunflower',3,3);const balance=g.sun;seconds(g,12.1);assert(g.sunDrops.some(s=>s.source==='sunflower'));assert.equal(g.sun,balance);const time=g.combatTime,timer=g.plants[0].productionTimer;g.paused=true;seconds(g,10);assert.equal(g.combatTime,time);assert.equal(g.plants[0].productionTimer,timer)});
test('Plant Food costs 1,2,3,4 and species behavior',()=>{const g=make();g.food=10;for(const cost of [1,2,3,4]){const before=g.food;assert(g.plantFood('peashooter'));assert.equal(before-g.food,cost)}assert.equal(g.levels.peashooter,5);assert(!g.plantFood('peashooter'));assert.equal(g.stats('peashooter').extraChance,.2);assert.equal(g.stats('repeater').extraChance,0)});
test('species upgrades and separate attack/production timers',()=>{const g=make(),r=g.stats('repeater').damage,s=g.stats('sunflower').productionInterval;take(g,'sharp');assert.equal(g.stats('repeater').damage,r);assert.equal(g.stats('peashooter').damage,31.2);take(g,'growth');assert.equal(g.stats('sunflower').productionInterval,s);take(g,'photo');assert(g.stats('sunflower').productionInterval<s);const hp=g.stats('peashooter').hp;take(g,'shell');assert.equal(g.stats('peashooter').hp,hp);assert.equal(g.stats('wallNut').hp,1300)});
test('mine arms then explodes, becomes uncounted immediately',()=>{const g=active();g.sun=1000;g.place('potatoMine',5,5);assert.equal(g.getPlantCost('potatoMine'),60);g.plants[0].age=5;g.zombies.push({x:5.5,y:5.5,hp:100,maxHp:100,speed:0,damage:0,cool:0,flash:0,uid:5});g.step(1/60);assert.equal(g.fieldCount('potatoMine'),0);assert.equal(g.getPlantCost('potatoMine'),50)});
test('combat, wave reward, choice, game-over emits once',()=>{let cleared=0,ended=0;const g=new Game(fresh(),()=>cleared++,()=>ended++);g.place('peashooter',8,5);g.startWave();g.queue=0;g.zombies=[{x:8.5,y:3.5,hp:20,maxHp:20,speed:0,damage:0,cool:0,flash:0,uid:77}];seconds(g,2);assert.equal(cleared,1);assert.equal(g.food,1);assert.equal(g.kills,1);assert(g.upgrade(g.choices[0]));assert.equal(g.countdown,9);g.startWave();g.hp=0;g.step(1/60);assert.equal(ended,1);seconds(g,1);assert.equal(ended,1)});
test('v1 migration preserves resources and mastery; import uses same validator',()=>{const v1={version:1,seeds:99,highestWave:8,totalRuns:4,kills:60,time:900,economy:2,fortress:3,mastery:4};const migrated=migrateSaveV1ToV2(v1);assert.equal(migrated.seeds,99);assert.equal(migrated.plantMastery.peashooter,4);assert.equal(migrated.plantMastery.repeater,4);assert.equal(migrated.version,2);assert.deepEqual(validate(v1),migrated);assert.deepEqual(validate(fresh()),fresh());assert.throws(()=>validate({...fresh(),seeds:-1}));assert.throws(()=>validate({...fresh(),plantMastery:{...fresh().plantMastery,wallNut:11}}));let stored=JSON.stringify(v1);globalThis.localStorage={getItem:()=>stored,setItem:(k,v)=>stored=v};assert.equal(read().version,2);assert(write(read()));assert.equal(JSON.parse(stored).version,2)});
test('weighted choices unique, valid, favor field and respect caps',()=>{const g=make();g.place('peashooter',5,5);for(let i=0;i<500;i++){const c=chooseUpgrades(g);assert.equal(c.length,3);assert.equal(new Set(c.map(u=>u.id)).size,3);assert(c.every(u=>UPGRADES.includes(u)));assert(c.some(u=>u.target==='peashooter'||u.target==='class:shooter'))}g.upgrades=Array(5).fill('sharp');assert(!chooseUpgrades(g).some(u=>u.id==='sharp'))});
test('all species / upgrades produce finite stats, caps and mastery isolation',()=>{const g=make();for(const u of UPGRADES)for(let i=0;i<u.maxStacks&&i<5;i++)g.upgrades.push(u.id);for(const p of PLANTS){g.levels[p.id]=5;const s=g.stats(p);for(const v of Object.values(s))if(typeof v==='number')assert(Number.isFinite(v));if(s.attackInterval)assert(s.attackInterval>=.18);if(s.productionInterval)assert(s.productionInterval>=4);assert(s.range<=8);assert(s.costDiscount<=.25)}const h=make();h.meta.plantMastery.peashooter=10;assert.equal(h.stats('peashooter',{permanent:true}).damage,31.2);assert.equal(h.stats('peashooter').damage,26)});
console.log(tests+' test groups passed; '+UPGRADES.length+' upgrades.');
