import assert from 'node:assert/strict';import {Game} from '../dist/js/game.js';import {fresh,validate} from '../dist/js/save.js';import {PLANTS,UPGRADES} from '../dist/js/data.js';
let cleared=0,ended=0;const g=new Game(fresh(),()=>cleared++,()=>ended++);
assert(!g.place('peashooter',0,2));assert(!g.place('peashooter',9,6));assert(g.place('peashooter',8,5));assert(!g.place('sunflower',8,5));assert(g.place('sunflower',7,6));assert(g.startWave());assert(!g.startWave());
const costs=new Game(fresh(),()=>{},()=>{});costs.sun=10000;assert.equal(costs.getPlantCost('sunflower'),50);assert(costs.place('sunflower',2,2));assert.equal(costs.getPlantCost('sunflower'),60);assert(costs.place('sunflower',3,2));assert.equal(costs.getPlantCost('sunflower'),72);assert(costs.place('sunflower',4,2));assert.equal(costs.getPlantCost('sunflower'),86);assert(costs.place('peashooter',5,2));assert.equal(costs.getPlantCost('sunflower'),86);assert.equal(costs.getPlantCost('wallNut'),50);costs.plants.find(p=>p.id==='sunflower').hp=0;costs.step(1/60);assert.equal(costs.getPlantCost('sunflower'),72);costs.mods.costDiscount=.10;assert.equal(costs.getPlantCost('sunflower'),65);const shown=costs.getPlantCost('sunflower'),sunBefore=costs.sun;assert(costs.place('sunflower',6,2));assert.equal(sunBefore-costs.sun,shown);
const mine=new Game(fresh(),()=>{},()=>{});mine.sun=1000;assert.equal(mine.getPlantCost('potatoMine'),25);assert(mine.place('potatoMine',5,5));assert.equal(mine.getPlantCost('potatoMine'),30);mine.plants[0].age=4;mine.state='playing';mine.queue=1;mine.zombies=[{x:5.5,y:5.5,hp:100,maxHp:100,speed:0,damage:0,cool:0,flash:0,uid:99}];mine.step(1/60);assert.equal(mine.getPlantCost('potatoMine'),25);
const before=g.time;g.paused=true;g.step(1);assert.equal(g.time,before);g.paused=false;
g.queue=0;g.zombies=[{...{x:8.5,y:3.5,hp:20,maxHp:20,speed:0,damage:0,cool:0,flash:0},uid:77}];for(let i=0;i<300&&g.state==='playing';i++)g.step(1/60);assert.equal(cleared,1);assert.equal(g.food,1);assert.equal(g.kills,1);assert(g.upgrade(UPGRADES[0]));assert(g.plantFood('peashooter'));assert.equal(g.levels.peashooter,2);assert.equal(g.food,0);
g.startWave();g.hp=0;g.step(1/60);assert.equal(ended,1);g.step(1);assert.equal(ended,1);assert.deepEqual(validate(fresh()),fresh());assert.throws(()=>validate({...fresh(),seeds:-1}));assert.throws(()=>validate({...fresh(),mastery:11}));
for(const p of PLANTS){const t=new Game(fresh(),()=>{},()=>{});t.sun=10000;assert(t.place(p.id,5,5));t.startWave();for(let i=0;i<240;i++)t.step(1/60);assert(Number.isFinite(t.hp));}
console.log('PASS: placement, progressive per-species costs, removal, mine explosion, discount, combat, waves and save.');
